version: "3.9"
services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kancir_cosmetics
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
  php:
    image: php:8.2-apache
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: secret
      DB_NAME: kancir_cosmetics
      ENFORCE_FACTORIES_WHITELIST: "1"
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
volumes:
  dbdata: